### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ert485** [ChrisPenner/ChrisPenner.github.io#1]
"ALSO ON CHRIS PENNER FP" links (bottom of each post page) go to:

`chrispenner.com/post/xxxxxx` (missing an s in posts)

instead of:
`chrispenner.com/posts/xxxxxx`

![bug](https://user-images.githubusercontent.com/6201488/35000549-9f4a30ac-fadc-11e7-8389-d056db08b12a.png)

**Comment by ChrisPenner** [comment]
Ahh; good catch. looks like Disqus hasn't figured out the new site layout yet. 

I ran a migration, they say it could take a day for the caches to expire but hopefully that'll do it!

Nice work finding the repo for the site BTW haha.

Cheers and thanks for the tip!
